/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranscriptionRouteImport } from './routes/transcription'
import { Route as TextToSpeechRouteImport } from './routes/text-to-speech'
import { Route as LiveTranslationRouteImport } from './routes/live-translation'
import { Route as CaptioningRouteImport } from './routes/captioning'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TranscriptionRoute = TranscriptionRouteImport.update({
  id: '/transcription',
  path: '/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToSpeechRoute = TextToSpeechRouteImport.update({
  id: '/text-to-speech',
  path: '/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTranslationRoute = LiveTranslationRouteImport.update({
  id: '/live-translation',
  path: '/live-translation',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptioningRoute = CaptioningRouteImport.update({
  id: '/captioning',
  path: '/captioning',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/captioning': typeof CaptioningRoute
  '/live-translation': typeof LiveTranslationRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/transcription': typeof TranscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/captioning': typeof CaptioningRoute
  '/live-translation': typeof LiveTranslationRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/transcription': typeof TranscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/captioning': typeof CaptioningRoute
  '/live-translation': typeof LiveTranslationRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/transcription': typeof TranscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/captioning'
    | '/live-translation'
    | '/text-to-speech'
    | '/transcription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/captioning'
    | '/live-translation'
    | '/text-to-speech'
    | '/transcription'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/captioning'
    | '/live-translation'
    | '/text-to-speech'
    | '/transcription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaptioningRoute: typeof CaptioningRoute
  LiveTranslationRoute: typeof LiveTranslationRoute
  TextToSpeechRoute: typeof TextToSpeechRoute
  TranscriptionRoute: typeof TranscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transcription': {
      id: '/transcription'
      path: '/transcription'
      fullPath: '/transcription'
      preLoaderRoute: typeof TranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-speech': {
      id: '/text-to-speech'
      path: '/text-to-speech'
      fullPath: '/text-to-speech'
      preLoaderRoute: typeof TextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-translation': {
      id: '/live-translation'
      path: '/live-translation'
      fullPath: '/live-translation'
      preLoaderRoute: typeof LiveTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captioning': {
      id: '/captioning'
      path: '/captioning'
      fullPath: '/captioning'
      preLoaderRoute: typeof CaptioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaptioningRoute: CaptioningRoute,
  LiveTranslationRoute: LiveTranslationRoute,
  TextToSpeechRoute: TextToSpeechRoute,
  TranscriptionRoute: TranscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
